### ISSUE TITLE
Add a downstream cluster

### ISSUE THREAD

**Issue by thehejik** [rancher/fleet-e2e#18]
Goal of this will be adding downstream clusters into rancher to be available for fleet testing.

### Tasks:
Use ginkgo to provision cluster(s):
- [x] define cluster resource on local/rancher cluster
- [x] download k3d binary
- [x] provision k3d cluster(s)
- [x] import k3d cluster to rancher

**Comment by sbulage** [comment]
@thehejik can this be moved to done?
