### ISSUE TITLE
Connect QASE to Fleet e2e tests

### ISSUE THREAD

**Issue by mmartin24** [rancher/fleet-e2e#27]
# Task
We need to "connect" the [FLEET repository](https://app.qase.io/project/FLEET) of tests to Cypress so that it can identify the Qase numbers format and paste the results into QASE runs. 

Inspiration: https://app.qase.io/run/HIGHLANDER/dashboard/5

![Image](https://github.com/rancher/fleet-e2e/assets/37271841/a205a0b3-fdb8-4c13-b0e2-f72d1625978e)

**Comment by sbulage** [comment]
May be I can take a look at it.
