### ISSUE TITLE
Run tests on created PR

### ISSUE THREAD

**Issue by mmartin24** [rancher/fleet-e2e#28]
Related to https://github.com/rancher/fleet-e2e/issues/2

Prior merging a PR, the ci should:

- Trigger e2e tests on all rancher versions
- They should be green prior merging
- Block merge if red

In the future, we could narrow this to a selection (i.e: P0, smoke tests, ...) instead of full run

**Comment by thehejik** [comment]
This has been partially addressed by #42 and #43.
* only rancher head_2.8 is triggered
* we don't block the PR by the CI
