### ISSUE TITLE
Check fleet resources in webui after initial login

### ISSUE THREAD

**Issue by thehejik** [rancher/fleet-e2e#58]
related to #57 

I noticed that `fleet-agent` and `gitjob` are installed after performing initial login in Rancher over WebUI. Would be nice to block next cy tests execution by waiting for these fleet resources within `first_login_rancher.spec.ts` test.

**Comment by thehejik** [comment]
I guess this has been addressed by https://github.com/rancher/fleet-e2e/pull/64

@mmartin24 can we close?

**Comment by mmartin24** [comment]
> I guess this has been addressed by #64
> 
> @mmartin24 can we close?

thanks @thehejik .
This was tackled here: https://github.com/rancher/fleet-e2e/issues/63

Closing issues
