### ISSUE TITLE
Make CI work  for e2e tests

### ISSUE THREAD

**Issue by mmartin24** [rancher/fleet-e2e#6]
# Issue
After e2e addition (https://github.com/rancher/fleet-e2e), the CI is not working as shown [here](https://github.com/rancher/fleet-e2e/actions/runs/7706227693/job/21001440918):

Error log
```
Run gcloud compute instances create capi-ci-8361ffa1-81ff-4cdf-9d11-b3927a36ef1e \
ERROR: (gcloud.compute.instances.create) Could not fetch resource:
 - The resource 'projects/ei-container-eco/global/instanceTemplates/hosted-prov-e2e-ci-runner-spot-n2-highmem-16-gl-template-v1' was not found

Error: Process completed with exit code 1.
```

# Task
We need to find out what is missing / needed and adapt it.

- [x] runner template #8 
- [x] installation deps and tweaks #11 
- [x] ~cypress part trying to use rancher domain concatenated from IP in reverse order~ (it was problem with VPC firewall actually - solved)

**Comment by thehejik** [comment]
resolved by:
https://github.com/rancher/fleet-e2e/pull/8
https://github.com/rancher/fleet-e2e/pull/11
...cypress part left

**Comment by thehejik** [comment]
Cypress part (rancher endpoint unavailable for him) was solved by changing GPC VPC firewall rules. Closing as done.

Testrun is green https://github.com/rancher/fleet-e2e/actions/runs/7726913571
